### ISSUE TITLE
Modal window problem

### ISSUE THREAD

**Issue by magaton** [davidjbradshaw/iframe-resizer#105]
We have a self hosted Angularjs + Bootstrap app that we need to integrate within some ERP system.
Ideally we'd open our app inside the ERP's iframe and minimize integration effort, so that's how we found iframe-resizer project.
Lists / grids within iframe look good, and iframe gets resized beautifully.
However problems appear with modal window. We are using Boostrap 3 modal window with Angular.
So, when we click on the grid within iframe, modal window is opened, but it has different height than the page within iframe. And, unfortunately iframe is not adjusting. 
We tried in different browsers, but no luck.

is this a known issue and if so, is there any workaround you'd suggest?

Thanks in advance,
Milan

**Comment by albanm** [comment]
Hello,

FYI I've had some difficulties with bootstrap modals and iframe-resizer.

What worked in the end was to use the 'lowestElement' method, and to slightly modify the style like this:

```css
body.in-iframe .modal-dialog {
  // use padding instead of margin as the getBoundingClientRect method used by iframe-resizer
  // ignore margins. Fortunately the visual effect is the same.
  margin-top: 0px;
  margin-bottom: 0px;
  padding-top: 15px;
  padding-bottom: 15px;
}
```
